#
# Format:
# 
# <heroku_san shorthand name>:
#   app: <Heroku app name>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#
production: 
  app: meetuptours
  config:
    BUNDLE_WITHOUT: "development:test"
    GOOGLE_ANALYTICS: "UA-12345678-1"

staging:
  app: meetuptours-staging
  config: &default
    BUNDLE_WITHOUT: "development:test"

demo: 
  app: meetuptours-demo
  config: *default
